services:
  postgres:
    image: postgres:17.3
    environment:
      - POSTGRES_DB=tripr
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P4ssword!
    ports:
      - "5433:5432"

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"  # SMTP server port
      - "8025:8025"  # Web UI port
    restart: unless-stopped
