services:
  postgres:
    image: postgres:17.3
    environment:
      - POSTGRES_DB=tripr
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P4ssword!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynet

  mailpit:
    image: axllent/mailpit:v1.23
    ports:
      - "1025:1025"  # SMTP server port
      - "8025:8025"  # Web UI port
    restart: unless-stopped
    networks:
      - mynet

  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/tripr
    ports:
      - "8080:8080"
    profiles: [fullstack]
    depends_on:
      - postgres
    networks:
      - mynet

volumes:
  postgres_data:
networks:
  mynet:
    driver: bridge
